version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
      - etc:/etc/mysql/conf.d
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      [
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci'
      ]

volumes:
  data:
  etc:
