version: '3.3'

services:
  mongo:
    # image: mongo:latest # MongoDB 5.0+ requires a CPU with AVX support
    image: mongo:4.4.13
    container_name: test-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  data:
