version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: test-pg
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # cdc,https://stackoverflow.com/a/59416434
    command: 
      [ 
        'postgres', 
        '-c', 
        'wal_level=logical' 
      ]

volumes:
  data:
