version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: test-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - data:/data:rw
    command:
      [
        'redis-server',
        '--requirepass ${REDIS_PASSWORD}',
        '--appendonly yes'
      ]

volumes:
  data:
